### ISSUE TITLE
建议 视频 以 16:9 比例渲染，不必选择媒体选择器

### ISSUE THREAD

**Issue by hipi** [HaoOuBa/Joe#40]
目前大部分视频 都是 16:9 的比例，而且之前媒体选择器的方法，大部分情况 左右都有黑框

这边给出示例
```css
.joe-dplayer{
            width: 100%;
            padding-top: 56.25%;
            position: relative;
 }
 .joe_vplayer{
            position: absolute;
            width: 100%;
            height: 100%;
            border: none;
            top: 0;
            left: 0;
 }
```
```html
<div class="joe-dplayer">
    <iframe class="joe_vplayer" src="https://player.dogged.cn/player/?url=https://pro-video.xiaoheiban.cn/202106/46847ac4-d5d7-4be7-84dc-9014ea19effe.mp4"></iframe>
</div>
```
